#!/bin/bash

set -e

OUTPUT_FILE=asr.csv
# OUTPUT_FILE=asr-dev.csv

export LC_ALL=C

# Download and unzip raw FCC data from: http://wireless.fcc.gov/uls/data/complete/r_tower.zip
echo "Downloading latest ASR data"
wget http://wireless.fcc.gov/uls/data/complete/r_tower.zip -O r_tower.zip
unzip r_tower.zip CO.dat RA.dat

echo "Joining data"

echo 'Registration Number|Record Type|Content Indicator|File Number|Unique System Identifier|Coordinate Type|Latitude Degrees|Latitude Minutes|Latitude Seconds|Latitude Direction|Latitude_Total_Seconds|Longitude Degrees|Longitude Minutes|Longitude Seconds|Longitude Direction|Longitude_Total_Seconds|Record Type|Content Indicator|File Number|Unique System Identifier|Application Purpose|Previous Purpose|Input Source Code|Status Code|Date Entered|Date Received|Date Issued|Date Constructed|Date Dismantled|Date Action|Archive Flag Code|Version|Signature First Name|Signature Middle Initial|Signature Last Name|Signature Suffix|Signature Title|Invalid Signature|Structure_Street Address|Structure_City|Structure_State Code|||Height of Structure|Ground Elevation|Overall Height Above Ground|Overall Height AMSL|Structure Type|Date FAA Determination Issued|FAA Study Number|FAA Circular Number|Specification Option|Painting and Lighting|FAA EMI Flag|NEPA Flag' > asr-full.csv

sort -t'|' -k4 CO.dat > CO-sorted.dat
sort -t'|' -k4 RA.dat > RA-sorted.dat

join -t'|' -1 4 -2 4 CO-sorted.dat RA-sorted.dat | sed 's/||\r//g' >> asr-full.csv

echo "Filtering data"

echo 'ID,Latitude,Longitude,Height' > asr-tmp.csv
# cut -d'|' -f 5,11,16,46,24 asr.csv | sort -t'|' -k4 -r -g | sed 's/|/,/g' | uniq | head -111475 >> asr-min.csv

# $5: Unique System Identifier
# $6: Coordinate Type, A=Array, T=Tower
# $10: Latitude Direction
# $11: Latitude
# $15: Longitude Direction
# $16: Longitude
# $24: T=Terminated, G=Granted, C=Constructed, A=Cancelled, I=Dismantled
# $46: Height
# $48: GTOWER / LTOWER=LatticeTower / MAST / MTOWER / POLE / TANK / TOWER
awk -F'|' '{
    if($6 == "T" && $24 == "C" && $11 != "" && $16 != "" && $16 != "0.0") {
        printf("%s,", $5);
        if($10 == "N")
            printf("%s",$11);
        else
            printf("-%s",$11);
        printf ",";
        if($15 == "W")
            printf("-%s",$16);
        else
            printf("%s",$16);
        print "," $46;
    }
}' asr-full.csv | sort -t',' -k4 -r -g >> asr-tmp.csv

# Remove dups and trim
awk -F',' '{ if(a[$1]++ == 0 && $4 >= 60.9) print }' asr-tmp.csv > $OUTPUT_FILE

# GZip
echo "Zipping data"
gzip -c $OUTPUT_FILE > $OUTPUT_FILE.gz

# Upload to S3
echo "Uploading to S3"
s3cmd put $OUTPUT_FILE.gz s3://platypii/asr/v1/
s3cmd setacl --acl-public s3://platypii/asr/v1/$OUTPUT_FILE.gz
