#!/bin/bash

set -e

INPUT_FILE=data/asr.csv.gz
OUTPUT_FILE=asr.csv.gz

# Upload to S3
echo "Uploading to S3"
s3cmd put $INPUT_FILE s3://platypii/asr/v1/$OUTPUT_FILE
s3cmd setacl --acl-public s3://platypii/asr/v1/$OUTPUT_FILE
